#!/bin/sh
# A shell script to start cloudapi server

. ./functions

prog=../appserver/appserver.py
pidfile=./cloudapi_server.pid

[ -e $prog ]

start() {
    echo -n "Starting $prog: "
    daemon --user python --pidfile $pidfile "python $prog &>/dev/null & echo \$! > $pidfile"
    retval=$?
    echo
    return $retval 
}

stop() {
    echo -n $"Stopping $prog: "
    killproc -p $pidfile $prog
    retval=$?
    echo
    return $retval
}

restart() {
    stop
    start
}

rh_status() {
    status -p $pidfile $prog
}

rh_status_q() {
    rh_status >/dev/null 2>&1
}


case "$1" in
    start)
        rh_status_q && exit 0
        $1
        ;;
    stop)
        rh_status_q || exit 0
        $1
        ;;
    status)
        rh_status
        ;;
    restart)
        $1
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart}"
        exit 2
esac
exit $?
